create table if not exists public.profile (
  id int primary key default 1,
  name text not null,
  headline text,
  location text,
  avatar_url text,
  about text,
  focus text,
  updated_at timestamptz default now(),
  constraint single_profile check (id = 1)
);

create table if not exists public.highlights (
  id bigint generated by default as identity primary key,
  title text not null,
  description text not null,
  sort_order int default 0,
  created_at timestamptz default now()
);

create table if not exists public.photos (
  id bigint generated by default as identity primary key,
  title text not null,
  description text not null,
  image_url text not null,
  location text,
  sort_order int default 0,
  created_at timestamptz default now()
);

alter table public.profile enable row level security;
alter table public.highlights enable row level security;
alter table public.photos enable row level security;

create policy "Public profile read"
on public.profile for select
using (true);

create policy "Public highlights read"
on public.highlights for select
using (true);

create policy "Public photos read"
on public.photos for select
using (true);

create policy "Authenticated profile write"
on public.profile for all
using (auth.role() = 'authenticated')
with check (auth.role() = 'authenticated');

create policy "Authenticated highlights write"
on public.highlights for all
using (auth.role() = 'authenticated')
with check (auth.role() = 'authenticated');

create policy "Authenticated photos write"
on public.photos for all
using (auth.role() = 'authenticated')
with check (auth.role() = 'authenticated');

create policy "Public gallery images read"
on storage.objects for select
using (bucket_id = 'gallery');

create policy "Authenticated gallery image upload"
on storage.objects for insert
with check (bucket_id = 'gallery' and auth.role() = 'authenticated');

create policy "Authenticated gallery image update"
on storage.objects for update
using (bucket_id = 'gallery' and auth.role() = 'authenticated')
with check (bucket_id = 'gallery' and auth.role() = 'authenticated');

create policy "Authenticated gallery image delete"
on storage.objects for delete
using (bucket_id = 'gallery' and auth.role() = 'authenticated');

insert into public.profile (id, name, headline, location, about, focus)
values (
  1,
  'Mi perfil personal',
  'Tecnologia, analisis y fotografia desde celular',
  'Peru',
  'Soy una persona proactiva, responsable y comprometida con mi crecimiento personal y profesional. Me caracteriza una mentalidad de aprendizaje constante y la facilidad para adaptarme a distintos entornos de trabajo.',
  'Busco integrar tecnologia, analisis y creatividad para desarrollar proyectos funcionales, modernos y con impacto positivo.'
)
on conflict (id) do nothing;

insert into public.highlights (title, description, sort_order)
values
  ('Desarrollo de sistemas', 'Formacion en Desarrollo de Sistemas de Informacion, con capacidades en tecnologia, organizacion, analisis y resolucion de problemas.', 1),
  ('Fotografia y video', 'Me apasiona capturar momentos, crear contenido visual y transmitir ideas mediante recursos audiovisuales usando principalmente mi celular.', 2),
  ('Investigacion operativa', 'Estudio Investigacion Operativa para fortalecer mi pensamiento analitico, la toma de decisiones y el uso de modelos de optimizacion.', 3)
on conflict do nothing;
